# this workflow will run cron-job
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
name: cron
on:
  workflow_dispatch:
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
jobs:
  job1:
    runs-on: macos-latest
    steps:
      - run: |
          curl -o ~/myci2.sh -s \
              https://raw.githubusercontent.com/kaizhu256/myci2/alpha/myci2.sh
          . ~/myci2.sh
          shMyciInit
          sh ~/jslint_ci.sh shGitCmdWithGithubToken clone \
              https://github.com/kaizhu256/betadog __tmp1 \
              --branch=alpha --depth=1 --single-branch
          cd __tmp1
          cp .gitconfig .git/config
          sh jslint_ci.sh shBetadogEow

