# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
name: cron
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.htm
    # minute [0,59]
    # hour [0,23]
    # day of the month [1,31]
    # month of the year [1,12]
    # day of the week ([0,6] with 0=sunday)
    - cron: "0 * * * 1,2,3,4,5,6"
  workflow_dispatch:
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
jobs:
  job1:
    runs-on: macos-latest
    steps:
      - run: |
          curl -o ~/myci2.sh -s \
              https://raw.githubusercontent.com/kaizhu256/myci2/alpha/myci2.sh
          . ~/myci2.sh
          shMyciInit
          sh ~/jslint_ci.sh shGitCmdWithGithubToken clone \
              https://github.com/kaizhu256/betadog __tmp1 \
              --branch=alpha --depth=1 --single-branch
          cd __tmp1
          cp .gitconfig .git/config
          sh jslint_ci.sh shBetadogEod
